-- MySQL Script generated by MySQL Workbench
-- mer. 24 sept. 2014 19:02:18 CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spring1
-- -----------------------------------------------------
/*CREATE SCHEMA IF NOT EXISTS `spring1` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `spring1` ;*/

-- -----------------------------------------------------
-- Table `labo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labo` (
  `idlabo` INT NOT NULL,
  `courrielLabo` VARCHAR(60) NOT NULL,
  `nomLabo` VARCHAR(45) NOT NULL,
  `pwd` VARCHAR(64) NOT NULL,
  `sel` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idlabo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atelier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atelier` (
  `idatelier` INT NOT NULL,
  `nomAtelier` VARCHAR(45) NOT NULL,
  `dateAtelier` TIMESTAMP NOT NULL,
  `description` TEXT NOT NULL,
  `inscription` TINYINT(1) NOT NULL,
  `labo_idlabo` INT NOT NULL,
  PRIMARY KEY (`idatelier`, `labo_idlabo`),
  INDEX `fk_atelier_labo_idx` (`labo_idlabo` ASC),
  CONSTRAINT `fk_atelier_labo`
    FOREIGN KEY (`labo_idlabo`)
    REFERENCES `spring1`.`labo` (`idlabo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
